# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HoltLauryDecision.ui'
#
# Created: Tue Aug 30 10:44:59 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1024, 814)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_73 = QtGui.QHBoxLayout()
        self.horizontalLayout_73.setObjectName(_fromUtf8("horizontalLayout_73"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_73.addItem(spacerItem)
        self.label_91 = QtGui.QLabel(Dialog)
        self.label_91.setMinimumSize(QtCore.QSize(75, 17))
        self.label_91.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_91.setFrameShape(QtGui.QFrame.Box)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.horizontalLayout_73.addWidget(self.label_91)
        self.label_92 = QtGui.QLabel(Dialog)
        self.label_92.setMinimumSize(QtCore.QSize(350, 17))
        self.label_92.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_92.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_92.setFrameShape(QtGui.QFrame.Box)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.horizontalLayout_73.addWidget(self.label_92)
        self.label_93 = QtGui.QLabel(Dialog)
        self.label_93.setMinimumSize(QtCore.QSize(350, 17))
        self.label_93.setMaximumSize(QtCore.QSize(350, 16777215))
        self.label_93.setFrameShape(QtGui.QFrame.Box)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.horizontalLayout_73.addWidget(self.label_93)
        self.label_94 = QtGui.QLabel(Dialog)
        self.label_94.setMinimumSize(QtCore.QSize(100, 17))
        self.label_94.setMaximumSize(QtCore.QSize(100, 29))
        self.label_94.setFrameShape(QtGui.QFrame.Box)
        self.label_94.setScaledContents(False)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName(_fromUtf8("label_94"))
        self.horizontalLayout_73.addWidget(self.label_94)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_73.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_73)
        self.horizontalLayout_74 = QtGui.QHBoxLayout()
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem2)
        self.label_95 = QtGui.QLabel(Dialog)
        self.label_95.setMinimumSize(QtCore.QSize(75, 45))
        self.label_95.setMaximumSize(QtCore.QSize(75, 32))
        self.label_95.setFrameShape(QtGui.QFrame.Box)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName(_fromUtf8("label_95"))
        self.horizontalLayout_74.addWidget(self.label_95)
        self.HL_Q1OA = QtGui.QLabel(Dialog)
        self.HL_Q1OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q1OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q1OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q1OA.setText(_fromUtf8(""))
        self.HL_Q1OA.setObjectName(_fromUtf8("HL_Q1OA"))
        self.horizontalLayout_74.addWidget(self.HL_Q1OA)
        self.HL_Q1OB = QtGui.QLabel(Dialog)
        self.HL_Q1OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q1OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q1OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q1OB.setText(_fromUtf8(""))
        self.HL_Q1OB.setObjectName(_fromUtf8("HL_Q1OB"))
        self.horizontalLayout_74.addWidget(self.HL_Q1OB)
        self.HL_R1 = QtGui.QLineEdit(Dialog)
        self.HL_R1.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R1.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R1.setFont(font)
        self.HL_R1.setMaxLength(1)
        self.HL_R1.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R1.setObjectName(_fromUtf8("HL_R1"))
        self.horizontalLayout_74.addWidget(self.HL_R1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_75 = QtGui.QHBoxLayout()
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem4)
        self.label_96 = QtGui.QLabel(Dialog)
        self.label_96.setMinimumSize(QtCore.QSize(75, 45))
        self.label_96.setMaximumSize(QtCore.QSize(75, 32))
        self.label_96.setFrameShape(QtGui.QFrame.Box)
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName(_fromUtf8("label_96"))
        self.horizontalLayout_75.addWidget(self.label_96)
        self.HL_Q2OA = QtGui.QLabel(Dialog)
        self.HL_Q2OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q2OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q2OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q2OA.setText(_fromUtf8(""))
        self.HL_Q2OA.setObjectName(_fromUtf8("HL_Q2OA"))
        self.horizontalLayout_75.addWidget(self.HL_Q2OA)
        self.HL_Q2OB = QtGui.QLabel(Dialog)
        self.HL_Q2OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q2OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q2OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q2OB.setText(_fromUtf8(""))
        self.HL_Q2OB.setObjectName(_fromUtf8("HL_Q2OB"))
        self.horizontalLayout_75.addWidget(self.HL_Q2OB)
        self.HL_R2 = QtGui.QLineEdit(Dialog)
        self.HL_R2.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R2.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R2.setFont(font)
        self.HL_R2.setMaxLength(1)
        self.HL_R2.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R2.setObjectName(_fromUtf8("HL_R2"))
        self.horizontalLayout_75.addWidget(self.HL_R2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_76 = QtGui.QHBoxLayout()
        self.horizontalLayout_76.setObjectName(_fromUtf8("horizontalLayout_76"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem6)
        self.label_97 = QtGui.QLabel(Dialog)
        self.label_97.setMinimumSize(QtCore.QSize(75, 45))
        self.label_97.setMaximumSize(QtCore.QSize(75, 32))
        self.label_97.setFrameShape(QtGui.QFrame.Box)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.horizontalLayout_76.addWidget(self.label_97)
        self.HL_Q3OA = QtGui.QLabel(Dialog)
        self.HL_Q3OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q3OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q3OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q3OA.setText(_fromUtf8(""))
        self.HL_Q3OA.setObjectName(_fromUtf8("HL_Q3OA"))
        self.horizontalLayout_76.addWidget(self.HL_Q3OA)
        self.HL_Q3OB = QtGui.QLabel(Dialog)
        self.HL_Q3OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q3OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q3OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q3OB.setText(_fromUtf8(""))
        self.HL_Q3OB.setObjectName(_fromUtf8("HL_Q3OB"))
        self.horizontalLayout_76.addWidget(self.HL_Q3OB)
        self.HL_R3 = QtGui.QLineEdit(Dialog)
        self.HL_R3.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R3.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R3.setFont(font)
        self.HL_R3.setMaxLength(1)
        self.HL_R3.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R3.setObjectName(_fromUtf8("HL_R3"))
        self.horizontalLayout_76.addWidget(self.HL_R3)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_76)
        self.horizontalLayout_77 = QtGui.QHBoxLayout()
        self.horizontalLayout_77.setObjectName(_fromUtf8("horizontalLayout_77"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem8)
        self.label_98 = QtGui.QLabel(Dialog)
        self.label_98.setMinimumSize(QtCore.QSize(75, 45))
        self.label_98.setMaximumSize(QtCore.QSize(75, 32))
        self.label_98.setFrameShape(QtGui.QFrame.Box)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName(_fromUtf8("label_98"))
        self.horizontalLayout_77.addWidget(self.label_98)
        self.HL_Q4OA = QtGui.QLabel(Dialog)
        self.HL_Q4OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q4OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q4OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q4OA.setText(_fromUtf8(""))
        self.HL_Q4OA.setObjectName(_fromUtf8("HL_Q4OA"))
        self.horizontalLayout_77.addWidget(self.HL_Q4OA)
        self.HL_Q4OB = QtGui.QLabel(Dialog)
        self.HL_Q4OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q4OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q4OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q4OB.setText(_fromUtf8(""))
        self.HL_Q4OB.setObjectName(_fromUtf8("HL_Q4OB"))
        self.horizontalLayout_77.addWidget(self.HL_Q4OB)
        self.HL_R4 = QtGui.QLineEdit(Dialog)
        self.HL_R4.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R4.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R4.setFont(font)
        self.HL_R4.setMaxLength(1)
        self.HL_R4.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R4.setObjectName(_fromUtf8("HL_R4"))
        self.horizontalLayout_77.addWidget(self.HL_R4)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_77)
        self.horizontalLayout_78 = QtGui.QHBoxLayout()
        self.horizontalLayout_78.setObjectName(_fromUtf8("horizontalLayout_78"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_78.addItem(spacerItem10)
        self.label_99 = QtGui.QLabel(Dialog)
        self.label_99.setMinimumSize(QtCore.QSize(75, 45))
        self.label_99.setMaximumSize(QtCore.QSize(75, 32))
        self.label_99.setFrameShape(QtGui.QFrame.Box)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName(_fromUtf8("label_99"))
        self.horizontalLayout_78.addWidget(self.label_99)
        self.HL_Q5OA = QtGui.QLabel(Dialog)
        self.HL_Q5OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q5OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q5OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q5OA.setText(_fromUtf8(""))
        self.HL_Q5OA.setObjectName(_fromUtf8("HL_Q5OA"))
        self.horizontalLayout_78.addWidget(self.HL_Q5OA)
        self.HL_Q5OB = QtGui.QLabel(Dialog)
        self.HL_Q5OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q5OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q5OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q5OB.setText(_fromUtf8(""))
        self.HL_Q5OB.setObjectName(_fromUtf8("HL_Q5OB"))
        self.horizontalLayout_78.addWidget(self.HL_Q5OB)
        self.HL_R5 = QtGui.QLineEdit(Dialog)
        self.HL_R5.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R5.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R5.setFont(font)
        self.HL_R5.setMaxLength(1)
        self.HL_R5.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R5.setObjectName(_fromUtf8("HL_R5"))
        self.horizontalLayout_78.addWidget(self.HL_R5)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_78.addItem(spacerItem11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_79 = QtGui.QHBoxLayout()
        self.horizontalLayout_79.setObjectName(_fromUtf8("horizontalLayout_79"))
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_79.addItem(spacerItem12)
        self.label_100 = QtGui.QLabel(Dialog)
        self.label_100.setMinimumSize(QtCore.QSize(75, 45))
        self.label_100.setMaximumSize(QtCore.QSize(75, 32))
        self.label_100.setFrameShape(QtGui.QFrame.Box)
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName(_fromUtf8("label_100"))
        self.horizontalLayout_79.addWidget(self.label_100)
        self.HL_Q6OA = QtGui.QLabel(Dialog)
        self.HL_Q6OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q6OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q6OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q6OA.setText(_fromUtf8(""))
        self.HL_Q6OA.setObjectName(_fromUtf8("HL_Q6OA"))
        self.horizontalLayout_79.addWidget(self.HL_Q6OA)
        self.HL_Q6OB = QtGui.QLabel(Dialog)
        self.HL_Q6OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q6OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q6OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q6OB.setText(_fromUtf8(""))
        self.HL_Q6OB.setObjectName(_fromUtf8("HL_Q6OB"))
        self.horizontalLayout_79.addWidget(self.HL_Q6OB)
        self.HL_R6 = QtGui.QLineEdit(Dialog)
        self.HL_R6.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R6.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R6.setFont(font)
        self.HL_R6.setMaxLength(1)
        self.HL_R6.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R6.setObjectName(_fromUtf8("HL_R6"))
        self.horizontalLayout_79.addWidget(self.HL_R6)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_79.addItem(spacerItem13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_79)
        self.horizontalLayout_80 = QtGui.QHBoxLayout()
        self.horizontalLayout_80.setObjectName(_fromUtf8("horizontalLayout_80"))
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem14)
        self.label_101 = QtGui.QLabel(Dialog)
        self.label_101.setMinimumSize(QtCore.QSize(75, 45))
        self.label_101.setMaximumSize(QtCore.QSize(75, 32))
        self.label_101.setFrameShape(QtGui.QFrame.Box)
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName(_fromUtf8("label_101"))
        self.horizontalLayout_80.addWidget(self.label_101)
        self.HL_Q7OA = QtGui.QLabel(Dialog)
        self.HL_Q7OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q7OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q7OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q7OA.setText(_fromUtf8(""))
        self.HL_Q7OA.setObjectName(_fromUtf8("HL_Q7OA"))
        self.horizontalLayout_80.addWidget(self.HL_Q7OA)
        self.HL_Q7OB = QtGui.QLabel(Dialog)
        self.HL_Q7OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q7OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q7OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q7OB.setText(_fromUtf8(""))
        self.HL_Q7OB.setObjectName(_fromUtf8("HL_Q7OB"))
        self.horizontalLayout_80.addWidget(self.HL_Q7OB)
        self.HL_R7 = QtGui.QLineEdit(Dialog)
        self.HL_R7.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R7.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R7.setFont(font)
        self.HL_R7.setMaxLength(1)
        self.HL_R7.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R7.setObjectName(_fromUtf8("HL_R7"))
        self.horizontalLayout_80.addWidget(self.HL_R7)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_80.addItem(spacerItem15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_80)
        self.horizontalLayout_81 = QtGui.QHBoxLayout()
        self.horizontalLayout_81.setObjectName(_fromUtf8("horizontalLayout_81"))
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_81.addItem(spacerItem16)
        self.label_102 = QtGui.QLabel(Dialog)
        self.label_102.setMinimumSize(QtCore.QSize(75, 45))
        self.label_102.setMaximumSize(QtCore.QSize(75, 32))
        self.label_102.setFrameShape(QtGui.QFrame.Box)
        self.label_102.setAlignment(QtCore.Qt.AlignCenter)
        self.label_102.setObjectName(_fromUtf8("label_102"))
        self.horizontalLayout_81.addWidget(self.label_102)
        self.HL_Q8OA = QtGui.QLabel(Dialog)
        self.HL_Q8OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q8OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q8OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q8OA.setText(_fromUtf8(""))
        self.HL_Q8OA.setObjectName(_fromUtf8("HL_Q8OA"))
        self.horizontalLayout_81.addWidget(self.HL_Q8OA)
        self.HL_Q8OB = QtGui.QLabel(Dialog)
        self.HL_Q8OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q8OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q8OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q8OB.setText(_fromUtf8(""))
        self.HL_Q8OB.setObjectName(_fromUtf8("HL_Q8OB"))
        self.horizontalLayout_81.addWidget(self.HL_Q8OB)
        self.HL_R8 = QtGui.QLineEdit(Dialog)
        self.HL_R8.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R8.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R8.setFont(font)
        self.HL_R8.setMaxLength(1)
        self.HL_R8.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R8.setObjectName(_fromUtf8("HL_R8"))
        self.horizontalLayout_81.addWidget(self.HL_R8)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_81.addItem(spacerItem17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_81)
        self.horizontalLayout_82 = QtGui.QHBoxLayout()
        self.horizontalLayout_82.setObjectName(_fromUtf8("horizontalLayout_82"))
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_82.addItem(spacerItem18)
        self.label_103 = QtGui.QLabel(Dialog)
        self.label_103.setMinimumSize(QtCore.QSize(75, 45))
        self.label_103.setMaximumSize(QtCore.QSize(75, 32))
        self.label_103.setFrameShape(QtGui.QFrame.Box)
        self.label_103.setAlignment(QtCore.Qt.AlignCenter)
        self.label_103.setObjectName(_fromUtf8("label_103"))
        self.horizontalLayout_82.addWidget(self.label_103)
        self.HL_Q9OA = QtGui.QLabel(Dialog)
        self.HL_Q9OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q9OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q9OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q9OA.setText(_fromUtf8(""))
        self.HL_Q9OA.setObjectName(_fromUtf8("HL_Q9OA"))
        self.horizontalLayout_82.addWidget(self.HL_Q9OA)
        self.HL_Q9OB = QtGui.QLabel(Dialog)
        self.HL_Q9OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q9OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q9OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q9OB.setText(_fromUtf8(""))
        self.HL_Q9OB.setObjectName(_fromUtf8("HL_Q9OB"))
        self.horizontalLayout_82.addWidget(self.HL_Q9OB)
        self.HL_R9 = QtGui.QLineEdit(Dialog)
        self.HL_R9.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R9.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R9.setFont(font)
        self.HL_R9.setMaxLength(1)
        self.HL_R9.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R9.setObjectName(_fromUtf8("HL_R9"))
        self.horizontalLayout_82.addWidget(self.HL_R9)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_82.addItem(spacerItem19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_82)
        self.horizontalLayout_83 = QtGui.QHBoxLayout()
        self.horizontalLayout_83.setObjectName(_fromUtf8("horizontalLayout_83"))
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_83.addItem(spacerItem20)
        self.label_104 = QtGui.QLabel(Dialog)
        self.label_104.setMinimumSize(QtCore.QSize(75, 45))
        self.label_104.setMaximumSize(QtCore.QSize(75, 32))
        self.label_104.setFrameShape(QtGui.QFrame.Box)
        self.label_104.setAlignment(QtCore.Qt.AlignCenter)
        self.label_104.setObjectName(_fromUtf8("label_104"))
        self.horizontalLayout_83.addWidget(self.label_104)
        self.HL_Q10OA = QtGui.QLabel(Dialog)
        self.HL_Q10OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q10OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q10OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q10OA.setText(_fromUtf8(""))
        self.HL_Q10OA.setObjectName(_fromUtf8("HL_Q10OA"))
        self.horizontalLayout_83.addWidget(self.HL_Q10OA)
        self.HL_Q10OB = QtGui.QLabel(Dialog)
        self.HL_Q10OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q10OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q10OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q10OB.setText(_fromUtf8(""))
        self.HL_Q10OB.setObjectName(_fromUtf8("HL_Q10OB"))
        self.horizontalLayout_83.addWidget(self.HL_Q10OB)
        self.HL_R10 = QtGui.QLineEdit(Dialog)
        self.HL_R10.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R10.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R10.setFont(font)
        self.HL_R10.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.HL_R10.setMaxLength(1)
        self.HL_R10.setCursorPosition(1)
        self.HL_R10.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R10.setObjectName(_fromUtf8("HL_R10"))
        self.horizontalLayout_83.addWidget(self.HL_R10)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_83.addItem(spacerItem21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_83)
        self.horizontalLayout_84 = QtGui.QHBoxLayout()
        self.horizontalLayout_84.setObjectName(_fromUtf8("horizontalLayout_84"))
        spacerItem22 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_84.addItem(spacerItem22)
        self.label_105 = QtGui.QLabel(Dialog)
        self.label_105.setMinimumSize(QtCore.QSize(75, 45))
        self.label_105.setMaximumSize(QtCore.QSize(75, 32))
        self.label_105.setFrameShape(QtGui.QFrame.Box)
        self.label_105.setAlignment(QtCore.Qt.AlignCenter)
        self.label_105.setObjectName(_fromUtf8("label_105"))
        self.horizontalLayout_84.addWidget(self.label_105)
        self.HL_Q11OA = QtGui.QLabel(Dialog)
        self.HL_Q11OA.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q11OA.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q11OA.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q11OA.setText(_fromUtf8(""))
        self.HL_Q11OA.setObjectName(_fromUtf8("HL_Q11OA"))
        self.horizontalLayout_84.addWidget(self.HL_Q11OA)
        self.HL_Q11OB = QtGui.QLabel(Dialog)
        self.HL_Q11OB.setMinimumSize(QtCore.QSize(350, 45))
        self.HL_Q11OB.setMaximumSize(QtCore.QSize(350, 32))
        self.HL_Q11OB.setFrameShape(QtGui.QFrame.Box)
        self.HL_Q11OB.setText(_fromUtf8(""))
        self.HL_Q11OB.setObjectName(_fromUtf8("HL_Q11OB"))
        self.horizontalLayout_84.addWidget(self.HL_Q11OB)
        self.HL_R11 = QtGui.QLineEdit(Dialog)
        self.HL_R11.setMinimumSize(QtCore.QSize(100, 35))
        self.HL_R11.setMaximumSize(QtCore.QSize(100, 29))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.HL_R11.setFont(font)
        self.HL_R11.setMaxLength(1)
        self.HL_R11.setAlignment(QtCore.Qt.AlignCenter)
        self.HL_R11.setObjectName(_fromUtf8("HL_R11"))
        self.horizontalLayout_84.addWidget(self.HL_R11)
        spacerItem23 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_84.addItem(spacerItem23)
        self.verticalLayout_3.addLayout(self.horizontalLayout_84)
        self.gridLayout.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem24, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem25)
        self.pushButton_valider = QtGui.QPushButton(Dialog)
        self.pushButton_valider.setObjectName(_fromUtf8("pushButton_valider"))
        self.horizontalLayout_3.addWidget(self.pushButton_valider)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem26)
        self.gridLayout.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem27, 4, 0, 1, 1)
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem28, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem29)
        self.te_consignes = QtGui.QLabel(Dialog)
        self.te_consignes.setMinimumSize(QtCore.QSize(850, 100))
        self.te_consignes.setMaximumSize(QtCore.QSize(850, 100))
        self.te_consignes.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.te_consignes.setFrameShape(QtGui.QFrame.Box)
        self.te_consignes.setFrameShadow(QtGui.QFrame.Plain)
        self.te_consignes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.te_consignes.setMargin(10)
        self.te_consignes.setIndent(-1)
        self.te_consignes.setObjectName(_fromUtf8("te_consignes"))
        self.horizontalLayout_4.addWidget(self.te_consignes)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem30)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem31 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem31, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_91.setText(_translate("Dialog", "Question", None))
        self.label_92.setText(_translate("Dialog", "OPTION A", None))
        self.label_93.setText(_translate("Dialog", "OPTION B", None))
        self.label_94.setText(_translate("Dialog", "Votre choix", None))
        self.label_95.setText(_translate("Dialog", "1", None))
        self.HL_R1.setText(_translate("Dialog", "?", None))
        self.label_96.setText(_translate("Dialog", "2", None))
        self.HL_R2.setText(_translate("Dialog", "?", None))
        self.label_97.setText(_translate("Dialog", "3", None))
        self.HL_R3.setText(_translate("Dialog", "?", None))
        self.label_98.setText(_translate("Dialog", "4", None))
        self.HL_R4.setText(_translate("Dialog", "?", None))
        self.label_99.setText(_translate("Dialog", "5", None))
        self.HL_R5.setText(_translate("Dialog", "?", None))
        self.label_100.setText(_translate("Dialog", "6", None))
        self.HL_R6.setText(_translate("Dialog", "?", None))
        self.label_101.setText(_translate("Dialog", "7", None))
        self.HL_R7.setText(_translate("Dialog", "?", None))
        self.label_102.setText(_translate("Dialog", "8", None))
        self.HL_R8.setText(_translate("Dialog", "?", None))
        self.label_103.setText(_translate("Dialog", "9", None))
        self.HL_R9.setText(_translate("Dialog", "?", None))
        self.label_104.setText(_translate("Dialog", "10", None))
        self.HL_R10.setText(_translate("Dialog", "?", None))
        self.label_105.setText(_translate("Dialog", "11", None))
        self.HL_R11.setText(_translate("Dialog", "?", None))
        self.pushButton_valider.setText(_translate("Dialog", "Valider", None))
        self.te_consignes.setText(_translate("Dialog", "Texte explication", None))

